### ISSUE TITLE
Build is failing

### ISSUE THREAD

**Issue by strogonoff** [glossarist/migration-adapters#3]
For the last 3 weeks, apparently: https://github.com/glossarist/convert-glossarist.github.io/actions

**Comment by ronaldtse** [comment]
@strogonoff the build started failing at:
https://github.com/glossarist/migration-adapters/actions/runs/7212690748

Which is due to:
https://github.com/glossarist/migration-adapters/commit/1dae3dde098e9e2760025c254140decb53e7be81

You should know how to fix it...

**Comment by strogonoff** [comment]
@ronaldtse https://github.com/glossarist/migration-adapters/commit/1dae3dde098e9e2760025c254140decb53e7be81 doesn’t bear relevance, and the same build sequence works for me locally as well as ever.

**Comment by strogonoff** [comment]
Either way, I fixed the build on this repository. Now https://github.com/glossarist/convert.glossarist.org/issues/1 is failing, and I give up—it works on my machine, I hope someone more proficient with GHA than me can find the problem.
