### ISSUE TITLE
Repository naming

### ISSUE THREAD

**Issue by strogonoff** [glossarist/migration-adapters#4]
Not sure it should be named “convert-glossarist.github.io”, it’s a monorepo containing a number of things, among which is that website (the webgui package) but also CLI etc. The original name `glossarist/migration-adapters` was fine…

**Comment by ronaldtse** [comment]
Every GitHub Pages site is hosted by a single repository. If this is a monorepo containing many things, it should not have GitHub Pages enabled, and a separate GitHub Pages repository should be created (i.e. `convert.glossarist.org`).

**Comment by ronaldtse** [comment]
Closing this since the repository has been renamed.
