### ISSUE TITLE
Deployment failure due to "Resource not accessible by integration" error

### ISSUE THREAD

**Issue by ribose-jeffreylau** [glossarist/migration-adapters#8]
https://github.com/glossarist/migration-adapters/actions/runs/7246116844/job/19737512500#step:2:10

**Comment by ribose-jeffreylau** [comment]
Since `repo:` is defined, a `token:` must be provided.

**Comment by ronaldtse** [comment]
The secret of `GLOSSARIST_CI_PAT_TOKEN` can be used. Thanks!

**Comment by ribose-jeffreylau** [comment]
Fixed in f81a8e7e23c9a1769e8f31dbf0df446a9bbac266.
